-- Wrap current_setting('app.user_id', true) in (select ...) in the RLS policies so
-- Postgres evaluates it once per statement (an InitPlan) instead of once per row --
-- the documented RLS perf pattern. Covers USING and WITH CHECK (WITH CHECK runs on
-- every INSERT/UPDATE row, so it needs the same wrap). Predicate-equivalent (row
-- visibility unchanged). Generated by 'pgrls fix --rule PERF001' and verified on
-- Postgres 16 (PERF001 -> 0). Refs #2.

-- [PERF001] Wrap auth function call(s) in policy 'app_settings_user_isolation' on public.app_settings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY app_settings_user_isolation ON public.app_settings
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'courses_user_isolation' on public.courses so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY courses_user_isolation ON public.courses
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'deliverables_user_isolation' on public.deliverables so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY deliverables_user_isolation ON public.deliverables
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'email_verifications_user_isolation' on public.email_verifications so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY email_verifications_user_isolation ON public.email_verifications
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'events_user_isolation' on public.events so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY events_user_isolation ON public.events
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'exams_user_isolation' on public.exams so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY exams_user_isolation ON public.exams
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'file_index_user_isolation' on public.file_index so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY file_index_user_isolation ON public.file_index
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'lectures_user_isolation' on public.lectures so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY lectures_user_isolation ON public.lectures
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'oauth_auth_codes_user_isolation' on public.oauth_auth_codes so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY oauth_auth_codes_user_isolation ON public.oauth_auth_codes
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'oauth_tokens_user_isolation' on public.oauth_tokens so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY oauth_tokens_user_isolation ON public.oauth_tokens
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'password_resets_user_isolation' on public.password_resets so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY password_resets_user_isolation ON public.password_resets
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'schedule_slots_user_isolation' on public.schedule_slots so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY schedule_slots_user_isolation ON public.schedule_slots
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'study_topics_user_isolation' on public.study_topics so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY study_topics_user_isolation ON public.study_topics
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'tasks_user_isolation' on public.tasks so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY tasks_user_isolation ON public.tasks
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'user_secrets_user_isolation' on public.user_secrets so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY user_secrets_user_isolation ON public.user_secrets
    USING (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (user_id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'users_self_only' on public.users so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY users_self_only ON public.users
    USING (id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid))
    WITH CHECK (id = CAST((SELECT current_setting(CAST('app.user_id' AS text), TRUE)) AS uuid));
